kssh# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    Deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: fetch code
          uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: deploy
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HAIFA_STAGING_SERVER_IP }}
            username: ${{ secrets.HAIFA_STAGING_SERVER_DEPLOY_USR }}
            key: ${{ secrets.HAIFASECRET }}
            source: "target/HP-1.0-SNAPSHOT.jar"
            target: "haifa"
        - name: run jar via ssh
          uses: fifsky/ssh-action@master
          with:
            command: |
              cd ~/haifa/target
              java -jar HP-1.0-SNAPSHOT.jar
            host: ${{ secrets.HAIFA_STAGING_SERVER_IP }}
            user: ${{ secrets.HAIFA_STAGING_SERVER_DEPLOY_USR }}
            key: ${{ secrets.HAIFASECRET }}
